import { Geist, Geist_Mono, Manrope } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "FamilyFriends",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto flex h-dvh max-w-[375px] flex-col bg-white px-[18px] antialiased shadow-[0_4px_16px_0_rgba(19,21,68,0.06)]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
